# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160117_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
